version: "3.8"

networks:
  internal:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/app
      - ./app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal
    depends_on:
      - php

  php:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/app
    networks:
      - internal
